// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/m-j-majevsky/gophermart/internal/service"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGopherMartService creates a new instance of MockGopherMartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGopherMartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGopherMartService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGopherMartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGopherMartService is an autogenerated mock type for the GopherMartService type
type MockGopherMartService struct {
	mock.Mock
}

type MockGopherMartService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGopherMartService) EXPECT() *MockGopherMartService_Expecter {
	return &MockGopherMartService_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) AuthenticateUser(ctx context.Context, login string, password string) (int64, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGopherMartService_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockGopherMartService_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockGopherMartService_Expecter) AuthenticateUser(ctx any, login any, password any) *MockGopherMartService_AuthenticateUser_Call {
	return &MockGopherMartService_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, login, password)}
}

func (_c *MockGopherMartService_AuthenticateUser_Call) Run(run func(ctx context.Context, login string, password string)) *MockGopherMartService_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGopherMartService_AuthenticateUser_Call) Return(n int64, err error) *MockGopherMartService_AuthenticateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGopherMartService_AuthenticateUser_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (int64, error)) *MockGopherMartService_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) GetBalance(ctx context.Context, userID int64) (decimal.Decimal, decimal.Decimal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 decimal.Decimal
	var r1 decimal.Decimal
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (decimal.Decimal, decimal.Decimal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) decimal.Decimal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) decimal.Decimal); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGopherMartService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockGopherMartService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockGopherMartService_Expecter) GetBalance(ctx any, userID any) *MockGopherMartService_GetBalance_Call {
	return &MockGopherMartService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockGopherMartService_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *MockGopherMartService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGopherMartService_GetBalance_Call) Return(decimal1 decimal.Decimal, decimal11 decimal.Decimal, err error) *MockGopherMartService_GetBalance_Call {
	_c.Call.Return(decimal1, decimal11, err)
	return _c
}

func (_c *MockGopherMartService_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID int64) (decimal.Decimal, decimal.Decimal, error)) *MockGopherMartService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByNumber provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) GetOrderByNumber(ctx context.Context, number string) (int64, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, number)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGopherMartService_GetOrderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByNumber'
type MockGopherMartService_GetOrderByNumber_Call struct {
	*mock.Call
}

// GetOrderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockGopherMartService_Expecter) GetOrderByNumber(ctx any, number any) *MockGopherMartService_GetOrderByNumber_Call {
	return &MockGopherMartService_GetOrderByNumber_Call{Call: _e.mock.On("GetOrderByNumber", ctx, number)}
}

func (_c *MockGopherMartService_GetOrderByNumber_Call) Run(run func(ctx context.Context, number string)) *MockGopherMartService_GetOrderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGopherMartService_GetOrderByNumber_Call) Return(n int64, err error) *MockGopherMartService_GetOrderByNumber_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGopherMartService_GetOrderByNumber_Call) RunAndReturn(run func(ctx context.Context, number string) (int64, error)) *MockGopherMartService_GetOrderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserOrders provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) ListUserOrders(ctx context.Context, userID int64) ([]service.OrderDTO, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserOrders")
	}

	var r0 []service.OrderDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]service.OrderDTO, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []service.OrderDTO); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.OrderDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGopherMartService_ListUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserOrders'
type MockGopherMartService_ListUserOrders_Call struct {
	*mock.Call
}

// ListUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockGopherMartService_Expecter) ListUserOrders(ctx any, userID any) *MockGopherMartService_ListUserOrders_Call {
	return &MockGopherMartService_ListUserOrders_Call{Call: _e.mock.On("ListUserOrders", ctx, userID)}
}

func (_c *MockGopherMartService_ListUserOrders_Call) Run(run func(ctx context.Context, userID int64)) *MockGopherMartService_ListUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGopherMartService_ListUserOrders_Call) Return(orderDTOs []service.OrderDTO, err error) *MockGopherMartService_ListUserOrders_Call {
	_c.Call.Return(orderDTOs, err)
	return _c
}

func (_c *MockGopherMartService_ListUserOrders_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]service.OrderDTO, error)) *MockGopherMartService_ListUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithdrawals provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) ListWithdrawals(ctx context.Context, userID int64) ([]service.WithdrawalDTO, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawals")
	}

	var r0 []service.WithdrawalDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]service.WithdrawalDTO, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []service.WithdrawalDTO); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.WithdrawalDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGopherMartService_ListWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithdrawals'
type MockGopherMartService_ListWithdrawals_Call struct {
	*mock.Call
}

// ListWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockGopherMartService_Expecter) ListWithdrawals(ctx any, userID any) *MockGopherMartService_ListWithdrawals_Call {
	return &MockGopherMartService_ListWithdrawals_Call{Call: _e.mock.On("ListWithdrawals", ctx, userID)}
}

func (_c *MockGopherMartService_ListWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *MockGopherMartService_ListWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGopherMartService_ListWithdrawals_Call) Return(withdrawalDTOs []service.WithdrawalDTO, err error) *MockGopherMartService_ListWithdrawals_Call {
	_c.Call.Return(withdrawalDTOs, err)
	return _c
}

func (_c *MockGopherMartService_ListWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]service.WithdrawalDTO, error)) *MockGopherMartService_ListWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGopherMartService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockGopherMartService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGopherMartService_Expecter) Ping(ctx any) *MockGopherMartService_Ping_Call {
	return &MockGopherMartService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockGopherMartService_Ping_Call) Run(run func(ctx context.Context)) *MockGopherMartService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGopherMartService_Ping_Call) Return(err error) *MockGopherMartService_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGopherMartService_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockGopherMartService_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) RegisterUser(ctx context.Context, login string, password string) (int64, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGopherMartService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockGopherMartService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockGopherMartService_Expecter) RegisterUser(ctx any, login any, password any) *MockGopherMartService_RegisterUser_Call {
	return &MockGopherMartService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, login, password)}
}

func (_c *MockGopherMartService_RegisterUser_Call) Run(run func(ctx context.Context, login string, password string)) *MockGopherMartService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGopherMartService_RegisterUser_Call) Return(n int64, err error) *MockGopherMartService_RegisterUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGopherMartService_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (int64, error)) *MockGopherMartService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// UploadOrder provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) UploadOrder(ctx context.Context, orderNumber string, userID int64) error {
	ret := _mock.Called(ctx, orderNumber, userID)

	if len(ret) == 0 {
		panic("no return value specified for UploadOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, orderNumber, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGopherMartService_UploadOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadOrder'
type MockGopherMartService_UploadOrder_Call struct {
	*mock.Call
}

// UploadOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
//   - userID int64
func (_e *MockGopherMartService_Expecter) UploadOrder(ctx any, orderNumber any, userID any) *MockGopherMartService_UploadOrder_Call {
	return &MockGopherMartService_UploadOrder_Call{Call: _e.mock.On("UploadOrder", ctx, orderNumber, userID)}
}

func (_c *MockGopherMartService_UploadOrder_Call) Run(run func(ctx context.Context, orderNumber string, userID int64)) *MockGopherMartService_UploadOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGopherMartService_UploadOrder_Call) Return(err error) *MockGopherMartService_UploadOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGopherMartService_UploadOrder_Call) RunAndReturn(run func(ctx context.Context, orderNumber string, userID int64) error) *MockGopherMartService_UploadOrder_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawPoints provides a mock function for the type MockGopherMartService
func (_mock *MockGopherMartService) WithdrawPoints(ctx context.Context, userID int64, orderNo string, sum decimal.Decimal) error {
	ret := _mock.Called(ctx, userID, orderNo, sum)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawPoints")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, userID, orderNo, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGopherMartService_WithdrawPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawPoints'
type MockGopherMartService_WithdrawPoints_Call struct {
	*mock.Call
}

// WithdrawPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNo string
//   - sum decimal.Decimal
func (_e *MockGopherMartService_Expecter) WithdrawPoints(ctx any, userID any, orderNo any, sum any) *MockGopherMartService_WithdrawPoints_Call {
	return &MockGopherMartService_WithdrawPoints_Call{Call: _e.mock.On("WithdrawPoints", ctx, userID, orderNo, sum)}
}

func (_c *MockGopherMartService_WithdrawPoints_Call) Run(run func(ctx context.Context, userID int64, orderNo string, sum decimal.Decimal)) *MockGopherMartService_WithdrawPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 decimal.Decimal
		if args[3] != nil {
			arg3 = args[3].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGopherMartService_WithdrawPoints_Call) Return(err error) *MockGopherMartService_WithdrawPoints_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGopherMartService_WithdrawPoints_Call) RunAndReturn(run func(ctx context.Context, userID int64, orderNo string, sum decimal.Decimal) error) *MockGopherMartService_WithdrawPoints_Call {
	_c.Call.Return(run)
	return _c
}
