-- Начальная схема базы данных сервиса лояльности «Гофермарт»

-- Тип для статуса заказа.
-- Значения соответствуют внутренним статусам обработки заказа.
CREATE TYPE order_status AS ENUM ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED');

-- Таблица пользователей.
-- login уникален; password_hash хранит bcrypt-хеш пароля.
-- balance и withdrawn ведут текущий баланс и суммарное списание баллов.
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         VARCHAR(255)                    NOT NULL,
    CONSTRAINT users_login_key UNIQUE (login),
    password_hash VARCHAR(255)                    NOT NULL,
    balance       NUMERIC(12,2)                   NOT NULL DEFAULT 0,
    withdrawn     NUMERIC(12,2)                   NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ                     NOT NULL DEFAULT now()
);

-- Таблица заказов.
-- number — номер заказа (уникален глобально).
-- status хранит внутренний статус: NEW, PROCESSING, INVALID, PROCESSED.
-- accrual — начисленные баллы (заполняется при переходе в PROCESSED).
CREATE TABLE IF NOT EXISTS orders (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number      VARCHAR(32)   NOT NULL,
    CONSTRAINT orders_number_key UNIQUE (number),
    user_id     BIGINT        NOT NULL REFERENCES users(id),
    status      order_status  NOT NULL DEFAULT 'NEW',
    accrual     NUMERIC(12,2) NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_status  ON orders(status);

-- Таблица списаний баллов.
-- Каждая запись — факт списания баллов в счёт заказа.
CREATE TABLE IF NOT EXISTS withdrawals (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL REFERENCES users(id),
    order_number VARCHAR(32)  NOT NULL,
    sum          NUMERIC(12,2) NOT NULL,
    processed_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_withdrawals_user_id ON withdrawals(user_id);
