// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/m-j-majevsky/gophermart/internal/repository"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// BatchUpdateOrders provides a mock function for the type MockStorage
func (_mock *MockStorage) BatchUpdateOrders(ctx context.Context, updates []repository.OrderUpdate) error {
	ret := _mock.Called(ctx, updates)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpdateOrders")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []repository.OrderUpdate) error); ok {
		r0 = returnFunc(ctx, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_BatchUpdateOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdateOrders'
type MockStorage_BatchUpdateOrders_Call struct {
	*mock.Call
}

// BatchUpdateOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - updates []repository.OrderUpdate
func (_e *MockStorage_Expecter) BatchUpdateOrders(ctx any, updates any) *MockStorage_BatchUpdateOrders_Call {
	return &MockStorage_BatchUpdateOrders_Call{Call: _e.mock.On("BatchUpdateOrders", ctx, updates)}
}

func (_c *MockStorage_BatchUpdateOrders_Call) Run(run func(ctx context.Context, updates []repository.OrderUpdate)) *MockStorage_BatchUpdateOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []repository.OrderUpdate
		if args[1] != nil {
			arg1 = args[1].([]repository.OrderUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_BatchUpdateOrders_Call) Return(err error) *MockStorage_BatchUpdateOrders_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_BatchUpdateOrders_Call) RunAndReturn(run func(ctx context.Context, updates []repository.OrderUpdate) error) *MockStorage_BatchUpdateOrders_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateOrder(ctx context.Context, number string, userID int64) error {
	ret := _mock.Called(ctx, number, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, number, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockStorage_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - userID int64
func (_e *MockStorage_Expecter) CreateOrder(ctx any, number any, userID any) *MockStorage_CreateOrder_Call {
	return &MockStorage_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, number, userID)}
}

func (_c *MockStorage_CreateOrder_Call) Run(run func(ctx context.Context, number string, userID int64)) *MockStorage_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_CreateOrder_Call) Return(err error) *MockStorage_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, number string, userID int64) error) *MockStorage_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateUser(ctx context.Context, login string, passwordHash string) (int64, error) {
	ret := _mock.Called(ctx, login, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, login, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, login, passwordHash)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - passwordHash string
func (_e *MockStorage_Expecter) CreateUser(ctx any, login any, passwordHash any) *MockStorage_CreateUser_Call {
	return &MockStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, login, passwordHash)}
}

func (_c *MockStorage_CreateUser_Call) Run(run func(ctx context.Context, login string, passwordHash string)) *MockStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_CreateUser_Call) Return(n int64, err error) *MockStorage_CreateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, login string, passwordHash string) (int64, error)) *MockStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockStorage
func (_mock *MockStorage) GetBalance(ctx context.Context, userID int64) (decimal.Decimal, decimal.Decimal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 decimal.Decimal
	var r1 decimal.Decimal
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (decimal.Decimal, decimal.Decimal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) decimal.Decimal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) decimal.Decimal); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockStorage_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) GetBalance(ctx any, userID any) *MockStorage_GetBalance_Call {
	return &MockStorage_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockStorage_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetBalance_Call) Return(balance decimal.Decimal, withdrawn decimal.Decimal, err error) *MockStorage_GetBalance_Call {
	_c.Call.Return(balance, withdrawn, err)
	return _c
}

func (_c *MockStorage_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID int64) (decimal.Decimal, decimal.Decimal, error)) *MockStorage_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByNumber provides a mock function for the type MockStorage
func (_mock *MockStorage) GetOrderByNumber(ctx context.Context, number string) (int64, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, number)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetOrderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByNumber'
type MockStorage_GetOrderByNumber_Call struct {
	*mock.Call
}

// GetOrderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockStorage_Expecter) GetOrderByNumber(ctx any, number any) *MockStorage_GetOrderByNumber_Call {
	return &MockStorage_GetOrderByNumber_Call{Call: _e.mock.On("GetOrderByNumber", ctx, number)}
}

func (_c *MockStorage_GetOrderByNumber_Call) Run(run func(ctx context.Context, number string)) *MockStorage_GetOrderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetOrderByNumber_Call) Return(n int64, err error) *MockStorage_GetOrderByNumber_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_GetOrderByNumber_Call) RunAndReturn(run func(ctx context.Context, number string) (int64, error)) *MockStorage_GetOrderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockStorage
func (_mock *MockStorage) GetUserByLogin(ctx context.Context, login string) (repository.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(repository.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockStorage_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockStorage_Expecter) GetUserByLogin(ctx any, login any) *MockStorage_GetUserByLogin_Call {
	return &MockStorage_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *MockStorage_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockStorage_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetUserByLogin_Call) Return(user repository.User, err error) *MockStorage_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStorage_GetUserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (repository.User, error)) *MockStorage_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingOrderNumbers provides a mock function for the type MockStorage
func (_mock *MockStorage) ListPendingOrderNumbers(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingOrderNumbers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_ListPendingOrderNumbers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingOrderNumbers'
type MockStorage_ListPendingOrderNumbers_Call struct {
	*mock.Call
}

// ListPendingOrderNumbers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) ListPendingOrderNumbers(ctx any) *MockStorage_ListPendingOrderNumbers_Call {
	return &MockStorage_ListPendingOrderNumbers_Call{Call: _e.mock.On("ListPendingOrderNumbers", ctx)}
}

func (_c *MockStorage_ListPendingOrderNumbers_Call) Run(run func(ctx context.Context)) *MockStorage_ListPendingOrderNumbers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_ListPendingOrderNumbers_Call) Return(strings []string, err error) *MockStorage_ListPendingOrderNumbers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockStorage_ListPendingOrderNumbers_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockStorage_ListPendingOrderNumbers_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserOrders provides a mock function for the type MockStorage
func (_mock *MockStorage) ListUserOrders(ctx context.Context, userID int64) ([]repository.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserOrders")
	}

	var r0 []repository.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]repository.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []repository.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_ListUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserOrders'
type MockStorage_ListUserOrders_Call struct {
	*mock.Call
}

// ListUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) ListUserOrders(ctx any, userID any) *MockStorage_ListUserOrders_Call {
	return &MockStorage_ListUserOrders_Call{Call: _e.mock.On("ListUserOrders", ctx, userID)}
}

func (_c *MockStorage_ListUserOrders_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_ListUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_ListUserOrders_Call) Return(orders []repository.Order, err error) *MockStorage_ListUserOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockStorage_ListUserOrders_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]repository.Order, error)) *MockStorage_ListUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithdrawals provides a mock function for the type MockStorage
func (_mock *MockStorage) ListWithdrawals(ctx context.Context, userID int64) ([]repository.Withdrawal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawals")
	}

	var r0 []repository.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]repository.Withdrawal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []repository.Withdrawal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_ListWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithdrawals'
type MockStorage_ListWithdrawals_Call struct {
	*mock.Call
}

// ListWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) ListWithdrawals(ctx any, userID any) *MockStorage_ListWithdrawals_Call {
	return &MockStorage_ListWithdrawals_Call{Call: _e.mock.On("ListWithdrawals", ctx, userID)}
}

func (_c *MockStorage_ListWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_ListWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_ListWithdrawals_Call) Return(withdrawals []repository.Withdrawal, err error) *MockStorage_ListWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockStorage_ListWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]repository.Withdrawal, error)) *MockStorage_ListWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockStorage
func (_mock *MockStorage) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Ping(ctx any) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStorage_Ping_Call) Run(run func(ctx context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(err error) *MockStorage_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawPoints provides a mock function for the type MockStorage
func (_mock *MockStorage) WithdrawPoints(ctx context.Context, userID int64, orderNo string, sum decimal.Decimal) error {
	ret := _mock.Called(ctx, userID, orderNo, sum)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawPoints")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, userID, orderNo, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_WithdrawPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawPoints'
type MockStorage_WithdrawPoints_Call struct {
	*mock.Call
}

// WithdrawPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNo string
//   - sum decimal.Decimal
func (_e *MockStorage_Expecter) WithdrawPoints(ctx any, userID any, orderNo any, sum any) *MockStorage_WithdrawPoints_Call {
	return &MockStorage_WithdrawPoints_Call{Call: _e.mock.On("WithdrawPoints", ctx, userID, orderNo, sum)}
}

func (_c *MockStorage_WithdrawPoints_Call) Run(run func(ctx context.Context, userID int64, orderNo string, sum decimal.Decimal)) *MockStorage_WithdrawPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 decimal.Decimal
		if args[3] != nil {
			arg3 = args[3].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_WithdrawPoints_Call) Return(err error) *MockStorage_WithdrawPoints_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_WithdrawPoints_Call) RunAndReturn(run func(ctx context.Context, userID int64, orderNo string, sum decimal.Decimal) error) *MockStorage_WithdrawPoints_Call {
	_c.Call.Return(run)
	return _c
}
