// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/m-j-majevsky/gophermart/internal/accrual"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualClient creates a new instance of MockAccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAccrualClient is an autogenerated mock type for the AccrualClient type
type MockAccrualClient struct {
	mock.Mock
}

type MockAccrualClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClient) EXPECT() *MockAccrualClient_Expecter {
	return &MockAccrualClient_Expecter{mock: &_m.Mock}
}

// GetOrderAccrual provides a mock function for the type MockAccrualClient
func (_mock *MockAccrualClient) GetOrderAccrual(ctx context.Context, orderNumber string) (*accrual.OrderResponse, error) {
	ret := _mock.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderAccrual")
	}

	var r0 *accrual.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*accrual.OrderResponse, error)); ok {
		return returnFunc(ctx, orderNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *accrual.OrderResponse); ok {
		r0 = returnFunc(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accrual.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualClient_GetOrderAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderAccrual'
type MockAccrualClient_GetOrderAccrual_Call struct {
	*mock.Call
}

// GetOrderAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *MockAccrualClient_Expecter) GetOrderAccrual(ctx any, orderNumber any) *MockAccrualClient_GetOrderAccrual_Call {
	return &MockAccrualClient_GetOrderAccrual_Call{Call: _e.mock.On("GetOrderAccrual", ctx, orderNumber)}
}

func (_c *MockAccrualClient_GetOrderAccrual_Call) Run(run func(ctx context.Context, orderNumber string)) *MockAccrualClient_GetOrderAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrualClient_GetOrderAccrual_Call) Return(orderResponse *accrual.OrderResponse, err error) *MockAccrualClient_GetOrderAccrual_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockAccrualClient_GetOrderAccrual_Call) RunAndReturn(run func(ctx context.Context, orderNumber string) (*accrual.OrderResponse, error)) *MockAccrualClient_GetOrderAccrual_Call {
	_c.Call.Return(run)
	return _c
}
